# Set true colour
set-option -sa terminal-overrides ',xterm*:Tc'
set-option -sa terminal-features ',xterm-kitty:RGB'

# Set prefix
unbind C-b 
set -g prefix C-Space
bind C-space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Index window panes at 1 not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Open panes in current dir
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

#set -g @plugin 'catppuccin/tmux'
#set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha

set -g status-left '#[fg=blue,bold,bg=1e1e2e] il0ng • session #S •'
set -g status-right '#[fg=b4befe,bold,bg=1e1e2e]%a %d %b %l:%M:%p '

set -g status-justify left
set -g status-left-length 200
set -g status-right-length 200
set -g status-position top
set -g status-style 'bg=#1e1e2e'

set -g window-status-current-format '#[fg=white,bg=#1e1e2e] *#I #W'
set -g window-status-format '#[fg=#6e6e7e,bg=#1e1e2e] #I #W'
set -g window-status-last-style 'fg=white,bg=black'

# Enable mouse actions such as drag pane
set -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
